#version: '3.8'

name: events

services:
  events:
    restart: on-failure
    build: .
    ports:
      - "8004:8004"
    env_file:
      - .env  # Load the .env file
    volumes:
      - ./static:/app/static
  
